Fix: добавлен слой Attachment
Bara0803/AstonMovieCenter pull request #12
Opened 2023-09-15 17:22 UTC by Kompas13

2023-09-15 18:04 UTC, Semion3017 requested changes

2023-09-16 08:42 UTC, Kompas13 commented on src/main/java/com/green/cinema/controller/AttachmentController.java
> +import org.springframework.web.bind.annotation.*;
исправил

2023-09-16 08:50 UTC, Kompas13 commented on src/main/java/com/green/cinema/controller/AttachmentController.java
> +    @PreAuthorize("hasAnyAuthority('ADMIN')")
имправил

2023-09-16 09:00 UTC, Kompas13 commented on src/main/java/com/green/cinema/exception/AttachmentNotFoundException.java
> +        public static final String ATTACHMENT_NOT_FOUND = "Poster not found";
Исправил

2023-09-16 09:00 UTC, Kompas13 commented on src/main/java/com/green/cinema/entity/Attachment.java
> +    private Long filmId;*/
Исправил

2023-09-16 09:03 UTC, Kompas13 commented on src/main/java/com/green/cinema/service/impl/AttachmentServiceImpl.java
> +import com.green.cinema.exception.*;
исправил

2023-09-16 09:40 UTC, Bara0803 approved these changes

2023-09-16 09:42 UTC, Bara0803 approved these changes

2023-09-16 09:43 UTC, merged